CommonArgumentsの追加
n0stack/n0library pull request #5
Opened 2017-10-03 18:30 UTC by h-otter

close #3 

n0stack全体で共通すると考えられるコマンドライン引数を切り出しました。

## 使い方
 
例の通り

1.` get_common_args` の結果を親ArgumentParserとして登録
2. 適宜引数を追加
3. パース
4. パースした結果を使っていろいろ初期化

## 対応したもの

- logger
- mqのURL

## 今後

関数を2回呼ばなきゃいけないのはスマートではないため、デコレータなどを使うのが良いかもしれない

2017-10-04 06:53 UTC, Kurorororo commented
https://www.python.org/dev/peps/pep-0008/#package-and-module-names
PEP8 によるとモジュール名は lowercase の方がいいので `common_arguments.py` より `commonarguments.py` ないし `commonargs.py` なんかがいいんじゃないでしょうか？

2017-10-04 06:57 UTC, h-otter commented
同じところに 

> Underscores can be used in the module name if it improves readability. 

とあるのでアンダースコアは大丈夫だったと思います。

まぁ確かに長すぎる感じはしますね。

2017-10-04 06:59 UTC, Kurorororo commented
lowercase は推奨であってアンダースコアも許容されるのはそうなんだけど、この場合は lowercase の方が気持ちいいかなと思いました。
他の人はどう思うかな？

2017-10-06 03:08 UTC, h-otter commented
ディレクトリを `arguments/common.py` にしました

2017-10-06 04:22 UTC, Kurorororo commented on n0library/arguments/common.py
> +                          default="/var/log/n0stack/n0core/porter-flat.log",
ここで porter/type/flat がハードコードされてるのは暫定的な処置かな？
それ以外は LGTM

2017-10-06 04:52 UTC, h-otter commented on n0library/arguments/common.py
> +                          default="/var/log/n0stack/n0core/porter-flat.log",
あ、みすです

治します :pray:

2017-10-06 05:02 UTC, kyontan commented on n0library/arguments/common.py
> +                          default="waring",
type: `waring`

2017-10-06 05:02 UTC, kyontan commented on n0library/arguments/common.py
> +                          default="waring",
typo: `waring`

2017-10-06 05:04 UTC, kyontan requested changes
typoが1箇所あって動かなかったですが、そこだけ直したら動いたのでそこだけ直してもらえればLGTMです 👍

2017-10-06 07:25 UTC, h-otter commented
ArgumentParserを継承する形に変更しました

2017-10-06 08:58 UTC, Kurorororo approved these changes

2017-10-06 09:26 UTC, kyontan approved these changes

2017-10-06 09:27 UTC, kyontan commented
LGTM! :tada:

2017-10-06 09:27 UTC, merged